package discord.enums;

import discord.util.BitFlagSet.BitFlag;

public enum Permission implements BitFlag {
	CREATE_INSTANT_INVITE,
	KICK_MEMBERS,
	BAN_MEMBERS,
	ADMINISTRATOR,
	MANAGE_CHANNELS,
	MANAGE_GUILD,
	ADD_REACTIONS,
	VIEW_AUDIT_LOG,
	PRIORITY_SPEAKER,
	STREAM,
	VIEW_CHANNEL,
	SEND_MESSAGES,
	SEND_TTS_MESSAGES,
	MANAGE_MESSAGES,
	EMBED_LINKS,
	ATTACH_FILES,
	READ_MESSAGE_HISTORY,
	MENTION_EVERYONE,
	USE_EXTERNAL_EMOJIS,
	VIEW_GUILD_INSIGHTS,
	CONNECT,
	SPEAK,
	MUTE_MEMBERS,
	DEAFEN_MEMBERS,
	MOVE_MEMBERS,
	USE_VAD,
	CHANGE_NICKNAME,
	MANAGE_NICKNAMES,
	MANAGE_ROLES,
	MANAGE_WEBHOOKS,
	MANAGE_GUILD_EXPRESSIONS,
	USE_APPLICATION_COMMANDS,
	REQUEST_TO_SPEAK,
	MANAGE_EVENTS,
	MANAGE_THREADS,
	CREATE_PUBLIC_THREADS,
	CREATE_PRIVATE_THREADS,
	USE_EXTERNAL_STICKERS,
	SEND_MESSAGES_IN_THREADS,
	USE_EMBEDDED_ACTIVITIES,
	MODERATE_MEMBERS,
	VIEW_CREATOR_MONETIZATION_ANALYTICS,
	USE_SOUNDBOARD,
	USE_EXTERNAL_SOUNDS(45),
	SEND_VOICE_MESSAGES(46);

	private final int bitIndex;

	private Permission() {
		bitIndex = ordinal();
	}

	private Permission(int bitIndex) {
		this.bitIndex = bitIndex;
	}

	@Override
	public int getBitIndex() {
		return bitIndex;
	}
}
